/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package twitchapplication;

import java.awt.Color;
import java.util.HashMap;
import javax.swing.WindowConstants;

/**
 *
 * @author Toby
 */
public class ConfigWindow extends javax.swing.JFrame {

    private TwitchController twc;
    
    /**
     * Creates new form ConfigWindow
     */
    public ConfigWindow(TwitchController twc) {
        this.setUndecorated(true);
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        this.twc = twc;
    }
    
    public void setProperties(HashMap<String, String> paramsSet){
        
    }
    
    public HashMap<String, String> getProperties(){
        HashMap<String, String> saveProps = new HashMap<>();
        saveProps.put("DisableNotifications", ""+remTrayCheckbox.isSelected());
        saveProps.put("RememberUser", ""+remUsernameCheckbox.isSelected());
        saveProps.put("StartMinimized", ""+startMinimizedCheckbox.isSelected());
        saveProps.put("RememberPosition", ""+remPositionCheckbox.isSelected());
        saveProps.put("TimerUpdate", ""+getTimeout());
        saveProps.put("AutoLogin", ""+autoLoginCheckbox.isSelected());
        saveProps.put("PopoutVideo", ""+popoutVideoCheckbox.isSelected());
        saveProps.put("UndecoratedWindow", ""+decoratedCheckbox.isSelected());
        return saveProps;
    }
    
    public void enterProperties(HashMap<String, String> enterMap){
        remTrayCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("DisableNotifications")));
        remUsernameCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("RememberUser")));
        startMinimizedCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("StartMinimized")));
        remPositionCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("RememberPosition")));
        if(remUsernameCheckbox.isSelected()){
            autoLoginCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("AutoLogin")));
        }
        System.out.println(Boolean.parseBoolean(enterMap.get("UndecoratedWindow")));
        boolean b = Boolean.parseBoolean(enterMap.get("UndecoratedWindow"));
        decoratedCheckbox.setSelected(!b);
        popoutVideoCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("PopoutVideo")));
        decoratedCheckbox.setSelected(Boolean.parseBoolean(enterMap.get("UndecoratedWindow")));
    }

    public int getTimeout(){
        int x;
        switch(timerChangeList.getSelectedIndex()){
            case 0:
                x=15;
                break;
            case 1:
                x=30;
                break;
            case 2:
                x=60;
                break;
            case 3:
                x=120;
                break;
            default:
                x=30;
                break;
        }
        return x;
    }
    
    public void setTimeout(int timeout){
        switch(timeout){
            case 15:
               timerChangeList.setSelectedIndex(0);
                break;
            case 30:
               timerChangeList.setSelectedIndex(1);
                break;
            case 60:
               timerChangeList.setSelectedIndex(2);
                break;
            case 120:
               timerChangeList.setSelectedIndex(3);
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resizeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        popoutVideoCheckbox = new javax.swing.JCheckBox();
        timerChangeList = new javax.swing.JComboBox();
        timerChangeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        remUsernameCheckbox = new javax.swing.JCheckBox();
        remTrayCheckbox = new javax.swing.JCheckBox();
        decoratedCheckbox = new javax.swing.JCheckBox();
        remPositionCheckbox = new javax.swing.JCheckBox();
        autoLoginCheckbox = new javax.swing.JCheckBox();
        startMinimizedCheckbox = new javax.swing.JCheckBox();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resizeButton.setText("Back to origin");
        resizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10), new java.awt.Color(0, 0, 0))); // NOI18N

        popoutVideoCheckbox.setText("Popout Video");
        popoutVideoCheckbox.setToolTipText("Checing this option opens the stream in the \"popout\" window");

        timerChangeList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15 secs", "30 secs", "1 minute", "2 minutes" }));

        timerChangeButton.setText("Set update timer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(timerChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timerChangeList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(popoutVideoCheckbox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(popoutVideoCheckbox)
                .addGap(9, 9, 9)
                .addComponent(timerChangeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerChangeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 10), new java.awt.Color(0, 0, 0))); // NOI18N

        remUsernameCheckbox.setText("Remember username");
        remUsernameCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remUsernameCheckboxActionPerformed(evt);
            }
        });

        remTrayCheckbox.setText("Disable tray notifcations");

        decoratedCheckbox.setText("Hide Window Border");
        decoratedCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decoratedCheckboxActionPerformed(evt);
            }
        });

        remPositionCheckbox.setText("Remember position");

        autoLoginCheckbox.setText("Auto login");
        autoLoginCheckbox.setEnabled(false);

        startMinimizedCheckbox.setText("Start minimized");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remUsernameCheckbox)
                    .addComponent(remTrayCheckbox)
                    .addComponent(decoratedCheckbox)
                    .addComponent(remPositionCheckbox)
                    .addComponent(autoLoginCheckbox)
                    .addComponent(startMinimizedCheckbox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(remUsernameCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoLoginCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startMinimizedCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remTrayCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remPositionCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decoratedCheckbox))
        );

        resetButton.setText("Reset Settings");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Config");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeButtonActionPerformed
        twc.resetLocation(1);
    }//GEN-LAST:event_resizeButtonActionPerformed

    private void remUsernameCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remUsernameCheckboxActionPerformed
        if(twc.getUsername().isEmpty()){
            twc.showMessage(3, "No username entered");
            remUsernameCheckbox.setSelected(false);
            return;
        }
        if(remUsernameCheckbox.isSelected()){
            autoLoginCheckbox.setEnabled(true);
        } else {
            autoLoginCheckbox.setEnabled(false);
            autoLoginCheckbox.setSelected(false);
        }
    }//GEN-LAST:event_remUsernameCheckboxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        twc.showMessage(1, "Configuration saved!");
        twc.loadParams(getProperties());
        twc.snapProperties();
    }//GEN-LAST:event_saveButtonActionPerformed

    
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        if(TwitchApplication.getInstance().deleteParams()){
            twc.showMessage(1, "Config deleted!");
        } else {
            twc.showMessage(3, "Unable to delete file!");
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void decoratedCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decoratedCheckboxActionPerformed
        twc.showMessage(1, "Restart program for option to take effect!");
    }//GEN-LAST:event_decoratedCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoLoginCheckbox;
    private javax.swing.JCheckBox decoratedCheckbox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox popoutVideoCheckbox;
    private javax.swing.JCheckBox remPositionCheckbox;
    private javax.swing.JCheckBox remTrayCheckbox;
    private javax.swing.JCheckBox remUsernameCheckbox;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resizeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox startMinimizedCheckbox;
    private javax.swing.JButton timerChangeButton;
    private javax.swing.JComboBox timerChangeList;
    // End of variables declaration//GEN-END:variables
}
